services:
  memories:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: memories
    env_file:
      - .env
    volumes:
      - ./src:/app/src:rw
      - ./cache:/app/cache:rw
    command: npm run dev
    restart: unless-stopped
