services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TZ=America/New_York
      - APPRISE_URL=http://synology.lan:8000
      - NODE_ENV=production
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped
