version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: memories
    env_file:
      - .env
    volumes:
      - ./src:/app/src:rw
    command: npm run dev
    restart: unless-stopped
